return {
    "nvim-lua/plenary.nvim",
    "nvim-tree/nvim-web-devicons",
    "hrsh7th/nvim-cmp",
    "hrsh7th/cmp-nvim-lsp",
    "hrsh7th/cmp-path",
    "hrsh7th/cmp-buffer",
    "nvim-telescope/telescope.nvim",
    { "ThePrimeagen/harpoon", branch = "harpoon2" },
    "rose-pine/neovim",
    "nvim-lualine/lualine.nvim",
    "windwp/nvim-autopairs",
    "brenoprata10/nvim-highlight-colors",
    "tpope/vim-fugitive",
    "mbbill/undotree",
    "ojroques/vim-oscyank",
    "lewis6991/gitsigns.nvim",
    "nvim-neo-tree/neo-tree.nvim",
    "MunifTanjim/nui.nvim",
    { "romgrk/barbar.nvim", dependencies = { "nvim-tree/nvim-web-devicons" } },
    "numToStr/Comment.nvim",
    "folke/which-key.nvim",
}
